[bootstrap.packages]
"brew:fish" = "latest"
"brew:fisher" = "latest"
"brew:git" = "latest"
"brew:neovim" = "latest"
"brew:starship" = "latest"
"brew:terminal-notifier" = "latest"

[bootstrap.macos.dock]
show_recents = false

[bootstrap.macos.finder]
show_all_files = true
show_pathbar = true

[bootstrap.user]
login_shell = "/opt/homebrew/bin/fish"

[env]
_.path = "/opt/homebrew/bin"
