[tools]
jq = "latest" # NOTE: Required by done on Sway and Niri

[bootstrap.packages]
"pacman:curl" = "latest"
"pacman:fish" = "latest"
"pacman:fisher" = "latest"
"pacman:gcc" = "latest"
"pacman:git" = "latest"
"pacman:neovim" = "latest"
"pacman:openssh" = "latest"

[bootstrap.user]
login_shell = "/usr/bin/fish"
