[bootstrap.packages]
"brew-cask:1password" = "latest"
"brew-cask:1password-cli" = "latest"
"brew-cask:alacritty" = "latest"
"brew-cask:discord" = "latest"
"brew-cask:firefox" = "latest"
"brew-cask:font-symbols-only-nerd-font" = "latest"
"brew-cask:keymapp" = "latest"
"brew-cask:obsidian" = "latest"
"brew-cask:spotify" = "latest"
"brew:bat" = "latest"
"brew:eza" = "latest"
"brew:fastfetch" = "latest"
"brew:fd" = "latest"
"brew:fish" = "latest"
"brew:fisher" = "latest"
"brew:git" = "latest"
"brew:git-delta" = "latest"
"brew:neovide" = "latest"
"brew:ripgrep" = "latest"
"brew:television" = "latest"
"brew:zoxide" = "latest"

[bootstrap.user]
login_shell = "/opt/homebrew/bin/fish"
