[format.rules]
trailing-comment-alignment = true
trailing-comment-space-width = 1

[[schemas]]
path = "https://mise.jdx.dev/schema/mise.json"
include = ["mise.toml", "mise.*.toml", "**/mise/config.toml"]

# NOTE: Overrides bind to the preceding mise schema
[[schemas.overrides]]
targets = [
  "settings",
  "tools",
  "dotfiles",
  "bootstrap.packages",
  "bootstrap.directories",
  "bootstrap.files",
  "tasks",
]

[schemas.overrides.format.rules]
table-keys-order = "ascending"

[[schemas]]
path = "https://starship.rs/config-schema.json"
include = ["**/starship.toml"]
