[tools]
age = "latest"
fnox = "latest"
gh = "latest"
herdr = "latest"
hk = "latest"
lazygit = "latest"
neovim = "latest"
node = "latest"
python = "latest"
tealdeer = "latest"
tree-sitter = "latest" # LazyVim requirement
uv = "latest"
